const mockEvents = {
    city: {
      id: 1007700,
      city: 'München',
      lat: 48.14,
      lon: 11.58,
      state: '',
      country: 'de',
      zip: 'meetup3',
      member_count: 1257
    },
    events: [
      {
        created: 1559645940000,
        duration: 10800000,
        id: '262030083',
        name: 'Clean Code Session #35: Pattern Apocalypse',
        rsvp_limit: 100,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561654800000,
        local_date: '2019-06-27',
        local_time: '19:00',
        updated: 1559645976000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 85,
        venue: {
          id: 26433928,
          name: 'Carl Zeiss Meditec AG',
          lat: 48.09483337402344,
          lon: 11.52451229095459,
          repinned: true,
          address_1: 'Kistlerhofstraße. 75',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1411685347000,
          name: 'Munich Software Craft Community',
          id: 17214922,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'munich-software-craft-community',
          who: 'Software Crafters',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/munich-software-craft-community/events/262030083/',
        description: '<p>Uncle Bob\'s videos are the classics of the genre. They explain the craft, methods and reasons with absolute clarity. They are a great source of knowledge and motivation to become a cleaner coder. They are entertaining, perfect for the beginners but they also have enough ideas interesting for experienced programmers.</p> <p>The next sessions are dedicated to Design Patterns. We meet on the 27th of June to see episode 34',
        visibility: 'public'
      },
      {
        created: 1559192857000,
        duration: 10800000,
        id: '261889529',
        name: 'C++11 was only the beginning',
        rsvp_limit: 110,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561482000000,
        local_date: '2019-06-25',
        local_time: '19:00',
        rsvp_open_offset: 'PT336H',
        updated: 1559538505000,
        utc_offset: 7200000,
        waitlist_count: 113,
        yes_rsvp_count: 110,
        venue: {
          id: 26423626,
          name: 'Austin Fraser GmbH',
          lat: 48.141048431396484,
          lon: 11.566612243652344,
          repinned: true,
          address_1: 'Lenbachplatz 1',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1381869297000,
          name: 'MUC++',
          id: 10704512,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'MUCplusplus',
          who: 'C++ aficionados',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/MUCplusplus/events/261889529/',
        description: '<p>On June, 25th, we have the great honour to welcome Mateusz Pusz to our user group. Mateusz is a software architect, chief engineer, and security champion with more than 15 years of experience in designing, writing and maintaining C++ code for fun and living. He is also a contributor and an active voting member of the ISO C++ Committee (WG21) where, together with the best C++ experts in the world, he shapes the future of the C++ language.</p> <p>Abstract:<br/>C++ is the fastest programming language in the world, and it leaves no room for other languages below it (except assembler). That is why it gets more attention now than ever before. As a result, we observe an increasing speed of the C++ language evolution. C++11 was a game changer, but now it is considered an old language already. C++14 and C++17 provided many improvements that allow us to write portable, safer, and faster programs in a shorter time. The resulting source code is easier to reason about and maintain. Moreover, the C++20 is coming soon, and it is going to be a game changer again.</p> <p>In my talk, I provide a few typical legacy code examples that most of us write every day. I describe how those samples evolve with the changes introduced in the subsequent C++ language releases ranging from C++11 up to the major groundbreaking features of upcoming C++20. During the talk, the audience will learn how much easier, more robust, and safer is the code written using modern tools that we get with every new C++ release.</p> <p>Schedule:<br/>19:00 -- Welcome with Pizza and Drinks<br/>19:30 -- Welcome at Austin Fraser<br/>19:40 -- Lightning Talk<br/>19:50 -- Main talk by Mateusz Pusz<br/>~21:00 -- Open Discussions<br/>22:00 -- Official End</p> <p>Sponsor: Austin Fraser</p> ',
        visibility: 'public'
      },
      {
        created: 1561193957000,
        duration: 7200000,
        id: '262530441',
        name: 'Building Enterprise AI Pipelines with TensorFlow and Kubernetes',
        rsvp_limit: 100,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562864400000,
        local_date: '2019-07-11',
        local_time: '19:00',
        updated: 1561390096000,
        utc_offset: 7200000,
        waitlist_count: 4,
        yes_rsvp_count: 100,
        group: {
          created: 1469524975000,
          name: 'PyData Munich',
          id: 20225730,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'PyData-Munchen',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/PyData-Munchen/events/262530441/',
        description: '<p>Talk Summary:<br/>oward the end of 2015, Google released TensorFlow, which started out as just another numerical library, but has grown to become a de facto standard in AI technologies. TensorFlow received a lot of hype as part of its initial release, in no small part because it was released by Google. Despite the hype, there have been complaints on usability. Especially, for example, the fact that debugging was only possible after construction of the static execution graph. In addition to that, neural networks needed to be expressed as a set of linear algebra operations which was considered too low level by many practitioners. PyTorch and Keras addressed many of the flaws in TensorFlow and gained a lot of ground. TensorFlow 2.0 successfully addressed those complaints and promises to become the go-to framework for many AI problems.</p> <p>Romeo Kienzler introduces you to the most prominent changes in TensorFlow 2.0 and how you can use these new features successfully in your projects. He explores eager execution, parallelization strategies, the advantages of the tight high-level Keras integration, live neural network training monitoring using TensorBoard, automated hyper parameter optimization, model serving with TensorFlow service, TensorFlow.js, and TensorFlow Lite. He shares an outlook on TFX—where Google is planning to open source its complete AI pipeline—and contrasts it with existing de facto standard frameworks like Apache Spark.</p> <p>Speaker Bio:<br/>Romeo Kienzler is Chief Data Scientist at the IBM Center for Open Source Data and AI Technologies (CODAIT) in San Fransisco, owning the strategy lead for AI Model Training. He works as Associate Professor for artificial intelligence at the Swiss University of Applied Sciences Berne and his current research focus is on cloud-scale machine learning and deep learning using open source technologies including TensorFlow, Keras, DeepLearning4J, Apache SystemML and the Apache Spark stack. He also contributes to various open source projects. He regularly speaks at international conferences including significant publications in the area of data mining, machine learning and Blockchain technologies.</p> <p>Location TBA</p> <p>17:30 Welcome and Pizza<br/>18:00 What\'s new in TensorFlow 2.0<br/>18:30 Bu<br/>ild Enterprise AI Pipelines using KubeFlow</p> ',
        visibility: 'public',
        pro_is_email_shared: false
      },
      {
        created: 1561033244000,
        duration: 7200000,
        id: '262475607',
        name: 'Building Enterprise AI Pipelines with TensorFlow and Kubernetes',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562859000000,
        local_date: '2019-07-11',
        local_time: '17:30',
        updated: 1561200415000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 82,
        group: {
          created: 1400181332000,
          name: 'Big Data Developers in Munich',
          id: 14476282,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Big-Data-Developers-in-Munich',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/262475607/',
        description: '<p>Agenda:</p> <p>17:30 Welcome and Pizza<br/>18:00 What\'s new in TensorFlow 2.0<br/>18:30 Build Enterprise AI Pipelines using KubeFlow</p> <p>Meetup taking part with our friends from PyData, please take a look, they have very interesting talks as well</p> <p></p> ',
        visibility: 'public',
        pro_is_email_shared: false
      },
      {
        created: 1555409541000,
        duration: 7200000,
        id: '260666142',
        name: 'Fuckup Nights Munich - Vol. II 2019',
        rsvp_limit: 150,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561568400000,
        local_date: '2019-06-26',
        local_time: '19:00',
        rsvp_close_offset: 'PT168H',
        updated: 1556110482000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 122,
        venue: {
          id: 26328091,
          name: 'IHK Academy Munich',
          lat: 48.124412536621094,
          lon: 11.59816837310791,
          repinned: true,
          address_1: 'Orleansstraße 10-12',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1443688096000,
          name: 'TechDivision TechTalk München',
          id: 18985124,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'TechDivision-TechTalk-Munchen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/TechDivision-TechTalk-Munchen/events/260666142/',
        description: '<p>Bei diesem Event handelt es sich um eine inzwischen weltweite Bewegung, die mittlerweile in mehr als 300 Städten in über 80 Ländern weltweit stattfindet! Jetzt gibt es dieses Event auch offiziell in München!</p> <p>Fuckup Nights klingt anrüchig? Ist es aber nicht! An diesem Abend haben vier Personen das Wort, die zur Abwechslung mal nicht von großen Erfolgsgeschichten erzählen, sondern mit Witz, Humor und aller Offenheit davon berichten, wie es auch mal schief laufen kann - damit sind wir bei den sog. Fuck Ups.</p> <p>Schaut Euch einfach das Video dazu an: </p> <p>Ein paar Impressionen von der ersten Fuckup Night Munich in diesem Jahr bei HIRMER mit 270 Teilnehmern bekommt ihr unter nachfolgendem Link: </p> <p>Fehler passieren eben und das im privaten Umfeld wie auch im Job - vom Ein-Mann Betrieb bis hin zu globalen Konzernen, nur wird darüber häufig nicht oder kaum gesprochen. Genau das wollen wir ändern! Im Rahmen der Fuckup Nights, soll genau darüber ganz offen gesprochen und diskutiert werden!</p> <p>ABER WARUM DAS GANZE?<br/>Ganz einfach! Weil man bekanntlich aus Fehlern lernt! Etwas erst gar nicht zu versuchen ist am Ende viel schlechter, wie etwas auszuprobieren und dann zu scheitern. Also nur wenn man etwas wagt und ausprobiert, kann man erst sicher sein, ob es überhaupt funktioniert. Wir sind daher überzeugt davon, dass man aus den meisten Misserfolgen etwas gewinnen und mitnehmen kann. Daher werden wir sicherlich auch einen unserer unzähligen FuckUps präsentieren. Ganz offen und ohne Filter!</p> <p>Die „Fuckup-Nights“ sind also dazu da, öffentlich über schief gelaufenen Projekte, Arbeiten und Ideen zu sprechen und diese Erfahrung mit der Community zu teilen. In lockerer Atmosphäre werden an diesem Abend wertvolle Erfahrungen von erfolgreichen Managern, Unternehmen und Startups weitergegeben, um daraus zu lernen. Natürlich gibt´s auch Snacks und Getränke, damit das Ganze nicht zu trocken wird!</p> <p>Es warten einige Überraschungen... ;-)</p> <p>WICHTIG: Die Teilnahme ist ausschließlich nach vorheriger Anmeldung über nachfolgenden Link möglich:<br/>First come - first serve!</p> ',
        visibility: 'public'
      },
      {
        created: 1550634729000,
        duration: 5400000,
        id: 'hrtcsqyzjbmc',
        name: 'Weekend Coffee for Startup People',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561816800000,
        local_date: '2019-06-29',
        local_time: '16:00',
        updated: 1550634729000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 17,
        venue: {
          id: 26033912,
          name: 'Park Café',
          lat: 48.1423454284668,
          lon: 11.56462287902832,
          repinned: true,
          address_1: 'Sophienstraße 7',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1443569671000,
          name: 'StartupBlink München',
          id: 18980890,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'StartupBlink-Munchen',
          who: 'StartupBlinkers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/StartupBlink-Munchen/events/hrtcsqyzjbmc/',
        description: '<p>Any plans for the weekend?</p> <p>This event brings together a small group of local entrepreneurs over a cup of coffee, in a relaxing and informal atmosphere. It\'s your chance to make new connections, share advice, and brainstorm new ideas with the people that are trying to build a new project or start a freelancing career.</p> <p>This event is self-organized for the local startup community. If you arrive first at the cafe, just pick a table and post in the group comments below where you are sitting and how to identify you (e.g. shirt color).</p> <p>Are you interested in leading this event on a weekly basis? Send us a quick email to [masked] to get more details.</p> <p>Enjoy your coffee with new friends!</p> <p>_ _ _</p> <p>Do you Telegram?<br/>Join the conversation in our global startup chat and connect with entrepreneurs from all over the world. </p> ',
        how_to_find_us: 'Know a better location for this meetup? Just send us a message, and we\'ll change it for you!',
        visibility: 'public',
        pro_is_email_shared: false
      },
      {
        created: 1558698444000,
        duration: 28800000,
        id: '261732656',
        name: 'TW presents: XConf Europe 2019',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562223600000,
        local_date: '2019-07-04',
        local_time: '09:00',
        updated: 1559731944000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 25,
        venue: {
          id: 26020661,
          name: 'smartvillage GmbH',
          lat: 48.13064956665039,
          lon: 11.537812232971191,
          repinned: true,
          address_1: 'Ganghoferstraße 66b',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1413448074000,
          name: 'ThoughtWorks Munich',
          id: 17658472,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'ThoughtWorks-Muenchen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/261732656/',
        description: '<p>***GET YOUR TICKET HERE: ***</p> <p>What is XConf?</p> <p>No fluff. No filler. Just real tech.<br/>XConf is created by technologists for technologists, for people who care deeply about software and its impact on the world.<br/>Now in its 6th year, ThoughtWorks XConf will be hosted across the UK, Germany and Spain.</p> <p>Join us as we welcome Neal Ford, Director Software Architect, ThoughtWorks to the stage as our keynote speaker!</p> <p>At XConf you will:<br/>- Discover emerging technologies and practices, use cases, and real stories<br/>- Learn how to implement new technologies where you work and have greater impact<br/>- Hear from people who broke through seemingly insurmountable resistance to change<br/>- Talk with other interesting and ambitious technologists<br/>- Let go of previously-held assumptions and gain new perspectives</p> <p>This one-day, two-track event gives you in direct access to a diverse range of ThoughtWorks senior technologists working on our clients’ most complex challenges.</p> <p>Very important note: You can only attend after registration:</p> ',
        visibility: 'public'
      },
      {
        created: 1553803113000,
        duration: 10800000,
        id: '260154719',
        name: 'Built with Flutter - Share your Flutter story',
        rsvp_limit: 100,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1564675200000,
        local_date: '2019-08-01',
        local_time: '18:00',
        updated: 1559937533000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 72,
        venue: {
          id: 26112492,
          name: 'Google',
          lat: 48.143035888671875,
          lon: 11.541084289550781,
          repinned: true,
          address_1: 'Erika-Mann-Straße 33',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1543101111000,
          name: 'Flutter Munich',
          id: 30587470,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Flutter-Munich',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Flutter-Munich/events/260154719/',
        description: '<p>🏰 Have you built something with Flutter? This is the time to show it to the world! This event is focussing on Flutter stories. You can share what you created with Flutter and how your experience was.</p> <p>🍻We are going to have 5+ short Flutter stories.</p> <p>👩\u200d🎓🕺👩\u200d💻This event will not focus heavily on coding, so feel free to invite your product owner, designer or entrepreneur friends. We have an attendee limit of 100 people. 💃👷💂\u200d♀️</p> <p>LOCATION</p> <p>📍The event\'s location: Isar Valley @ Google Munich</p> <p>PRESENTATIONS</p> <p>🎤 Stefan Schaller and Julian Bissekkou from Tikkr<br/>Tikkr is a time tracking tool for small startups and freelancers. You can create and track tasks. You always have an overview of your time and statistics.<br/>Tikkr is a team of three: Stefan, Julian (mobile developers) and Tobi (web developer). They also develop a web app in AngularDart, this enables them to share code between the web and mobile app.<br/></p> <p>🎤 Wolfgang Strunk from SV Pullach/iteratec<br/>Have you ever built an app for a non-profit organization? The SV Pullach App lets you figure out the next games, insert them to your calendar, search for match locations and get overall team information.<br/>A no longer maintained iOS App was the trigger for a rebuild of the outdated Android App. Flutter\'s cross-platform approach allowed to give it a try, backed by Wolfgang\'s personal 5 day budget for innovation projects.</p> <p>🎤 Nils Schmidt from Glutyfree<br/>Glutyfree is an app to detect gluten in packaged-food using optical character recognition. It helps people who are dependent on a gluten-free diet or who follow a gluten-free lifestyle. The idea for the app originated because Nils\' friends always asked him whether a certain product is gluten-free. Now they can simply use Glutyfree.<br/></p> <p>🎤Julian Köpke from LIV-T/OilFox<br/>OilFox is a smart meter measuring the fill level of your oil tank. It can be retrofit to old tanks with no effort. Our customers can then monitor their oil usage on their phones using a cross-platform app which was previously written in React Native. With increasing technical debt and little time to maintain the app, Julian started to rewrite the app in Flutter as a pet project. The new app is now in an open beta phase.<br/></p> <p>CONTRIBUTE:</p> <p>🚀 We would like to hear about your personal pet projects, your work for a client or your company or open source libraries. The talks should be a good mixture of Flutter, technology, your product or service, your team, an overview of the greatest challenges along the way and a good story. You can share with us why you used Flutter, how you used it and what you built as long as you can do it in 11 minutes.</p> <p>🎤 Would you like to present? Please contact me if you, your company or your team is working on something awesome and using Flutter made shipping something great possible and you would like to share your story with us.</p> <p>🍕 Would you or your company like to host one of our upcoming events? Send me a message!</p> ',
        how_to_find_us: 'Isar Valley @ Google Munich. Get your badge at the lobby, we\'ll be there to show you where the event space is.',
        visibility: 'public'
      },
      {
        created: 1560520137000,
        duration: 10800000,
        id: '262314612',
        name: 'Pre TestBash Munich Meetup (Thursday)',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1568304000000,
        local_date: '2019-09-12',
        local_time: '18:00',
        updated: 1560520150000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 21,
        group: {
          created: 1478557022000,
          name: 'Ministry of Testing Munich',
          id: 21079013,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Ministry-of-Testing-Munich',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Ministry-of-Testing-Munich/events/262314612/',
        description: '<p>TestBash is returning to Munich for a third time!</p> <p>This time we have expanded to include a workshop day on 12th September too. In the tradition of TestBash, we will be having a meetup in the evening after the workshops. You don\'t need to have purchased a workshop ticket to attend the meetup, it\'s open to everyone!</p> <p>This is an excellent opportunity to get to say hello to some of the other attendees and speakers before the event on Friday and hear what other attendees of the workshop day have learned.</p> <p>If you haven\'t got your ticket yet, or you want to find out more, check the Ministry of Testing website</p> ',
        visibility: 'public'
      },
      {
        created: 1556020226000,
        duration: 7200000,
        id: '260849718',
        name: 'AfterWERK meets Munich Startup powered by Lexware',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561651200000,
        local_date: '2019-06-27',
        local_time: '18:00',
        updated: 1560769956000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 124,
        venue: {
          id: 19782872,
          name: 'WERK1',
          lat: 48.12442398071289,
          lon: 11.607309341430664,
          repinned: true,
          address_1: 'Grafinger Straße 6',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1458124246000,
          name: 'WERK1',
          id: 19716609,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'WERK1munich',
          who: 'movers and shakers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/WERK1munich/events/260849718/',
        description: '<p>Once per month the Munich Startup Community meets at WERK1 for the famous „Feierabend-Bier“, snacks and wine!</p> <p>Join us for 1-2 pitches &amp; networking. If you are interested in pitching yourself write to [masked].</p> <p>In a nutshell<br/>– Thursday, 27th June 2019 || 6pm<br/>– Informal networking with snacks &amp; drinks<br/>– Meet Munich Entrepreneurs Startups &amp; Freelancers<br/>– max. 2 startup pitches, 5 minutes each</p> ',
        how_to_find_us: 'access by car only via Piusstraße, coming by S-Bahn Ostbahnhof enter Werksviertel on Speicherstraße.',
        visibility: 'public'
      },
      {
        created: 1559719136000,
        duration: 21600000,
        id: '262058390',
        name: 'Kotlin/Everywhere Munich',
        rsvp_limit: 200,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562245200000,
        local_date: '2019-07-04',
        local_time: '15:00',
        updated: 1560609466000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 117,
        venue: {
          id: 26437840,
          name: 'BMW-Vierzylinder',
          lat: 48.176971435546875,
          lon: 11.560166358947754,
          repinned: true,
          city: 'Munich',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1421043158000,
          name: 'Kotlin User Group Munich - KUG Munich',
          id: 18325305,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Kotlin-User-Group-Munich',
          who: 'KUG-Hacker',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Kotlin-User-Group-Munich/events/262058390/',
        description: '<p>This event is a joint event organized together with the GDG Munich Android and the Kotlin User Group Munich.</p> <p>PLEASE RSVP ONLY TO ONE GROUP!</p> <p>If this group is full, check the other one there might be still spots left:<br/></p> <p>Places are limited, please cancel your RSVP if you can’t make it so someone else can take your place.</p> <p>Event schedule might still change! Please follow these twitter accounts for details:<br/>for updates!</p> <p>15:00 Doors open<br/>15:30 Welcome<br/>15:40 Florina Muntenescu, Google - Extend Your Vocabulary with Kotlin Language Features<br/>16:25 Svetlana Isakova, JetBrains - New Type Inference and Related Language Features<br/>17:25 Shagen Ogandzhanian, JetBrains - What\'s New in Kotlin/JS interop<br/>17:55 Food Break<br/>18:40 Wojtek Kaliciński, Google - Kotlin Multiplatform<br/>19:40 Jossi Wolf, Snapp Mobile - Building SDKs - The Kotlin Way<br/>20:10 Marcin Moskala, Kt. Academy - Understanding Kotlin Coroutines<br/>21:00 End</p> <p>Please do take note on the community guidelines for the event:<br/></p> ',
        visibility: 'public'
      },
      {
        created: 1560409946000,
        duration: 3600000,
        id: '262280794',
        name: 'Chat with Malt-CEO Vincent Huguet',
        rsvp_limit: 20,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561395600000,
        local_date: '2019-06-24',
        local_time: '19:00',
        updated: 1560409946000,
        utc_offset: 7200000,
        waitlist_count: 5,
        yes_rsvp_count: 20,
        venue: {
          id: 26453533,
          name: 'Westermühlstraße 10',
          lat: 48.12853240966797,
          lon: 11.56916332244873,
          repinned: false,
          address_1: 'Westermühlstraße 10',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1552473723000,
          name: 'Freelancing in Deutschland',
          id: 31379005,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Freelancing-in-Deutschland',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Freelancing-in-Deutschland/events/262280794/',
        description: '<p>Ein etwas anderes AfterMalt 🙂</p> <p>Lerne wie immer in entspannter Atmosphäre und bei einem Drink andere Freelancer und das Malt-Team persönlich kennen.</p> <p>Dieses Mal wird unser CEO Vincent Huguet persönlich vor Ort sein und sich all euren Fragen stellen.</p> <p>Es gibt etwas, was du über Malt und die Gründung der Plattform wissen möchtest? Dann komm vorbei und tausche dich mit uns aus! Zu finden sind wir in der Korner Bar.</p> <p>Wir freuen uns darauf, dich wiederzusehen oder kennenzulernen!</p> ',
        visibility: 'public'
      },
      {
        created: 1559750276000,
        duration: 7200000,
        id: '262067176',
        name: 'Einführung in die XR/AR/VR - Entwicklung',
        rsvp_limit: 50,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562169600000,
        local_date: '2019-07-03',
        local_time: '18:00',
        updated: 1559750299000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 44,
        venue: {
          id: 25766821,
          name: 'medialesson - Büro München',
          lat: 48.153099060058594,
          lon: 11.583580017089844,
          repinned: true,
          address_1: 'Leopoldstr. 8-10',
          address_2: 'c/o Nutrion Coworking Space',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1520252901000,
          name: 'Software, Technology & Design Meetup München',
          id: 27731423,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Software-Technology-Meetup-Munchen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Software-Technology-Meetup-Munchen/events/262067176/',
        description: '<p>Was wir unternehmen werden: Weiter geht’s in diesem Jahr mit spannenden Meetups in den Büroräumen unseres Sponsors medialesson in München! Dieses ist unser drittes Meetup in diesem Jahr und ersetzt das leider ausgefallene Meetup zum selben Thema vom Mai.</p> <p>Wir widmen uns heute einem Thema, das für viele Software-Entwickler, die sich mit der Gestaltung benutzerfreundlicher und innovativer Frontends befassen, sicherlich von großer Bedeutung ist: Wie kann ich mit Virtual, Augmented und Mixed Reality die User Experience verbessern und für mobile Anwendungen im Raum neuartige Darstellungsmethoden umsetzen?</p> <p>Und hier zu allererst: Welche Grundlagen und Tools gehören zur VR-/AR-App-Entwicklung? Dino Fejzagic, Mixed Reality-Entwickler bei der medialesson GmbH, stellt in seinem Vortrag die VR- und AR-App-Entwicklung in vielen ihrer Facetten vor und beschreibt, mit welchen Tools gute Ergebnisse erreicht werden können. Auch demonstriert Dino einige Mixed Reality-Apps in praktischen Beispielen. In einer anschließenden Diskussionsrunde, wollen wir uns gemeinsam der Frage widmen, wohin uns diese Reise noch führen kann.</p> <p>Dieses Meetup richtet sich an Software-Entwickler und IT-Architekten, die einen ersten Einstieg in die VR-/AR-Software-Entwicklung finden möchten.</p> <p>-.-.-</p> <p>Agenda</p> <p>18:00 Uhr - 18:30 Uhr: Kennenlernen bei Pizza und Kaltgetränken</p> <p>18:30 Uhr - 20:00 Uhr: Vortrag Dino Fejzagic mit praktischen Beispielen</p> <p>20:00 Uhr - 20:30 Uhr (oder länger, je nach Interesse): Offene Runde / Diskussion</p> <p>Falls jemand einen weiteren Vortrag zum Thema beisteuern möchte, wäre dies im Anschluss an den ersten Vortag möglich. Genügend Zeit für die Diskussionsrunde ist eingeplant. Meldet euch gerne einfach bei Dino!</p> <p>Catering: Pizza und Getränke werden auch diesmal von medialesson gesponsert. Vielen Dank dafür!</p> ',
        how_to_find_us: 'Eingang über Treppe ins Gebäude Leo 8 und dann die Wendeltreppe hinunter ins Basement. Erste Glastür rechts Nutrion.',
        visibility: 'public'
      },
      {
        created: 1553800423000,
        duration: 10800000,
        id: '260153576',
        name: 'Flutter Study Jam',
        rsvp_limit: 70,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1563465600000,
        local_date: '2019-07-18',
        local_time: '18:00',
        updated: 1560768570000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 44,
        venue: {
          id: 26041200,
          name: 'SinnerSchrader Deutschland GmbH',
          lat: 48.15207290649414,
          lon: 11.583761215209961,
          repinned: true,
          address_1: 'Schackstraße 3',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1543101111000,
          name: 'Flutter Munich',
          id: 30587470,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Flutter-Munich',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Flutter-Munich/events/260153576/',
        description: '<p>I’d like to invite all of you to our first-ever study jam/coding night. It’s going to be a very laid-back event, with great conversations, drinks, and food. The concept is simple: we meet and we build beautiful apps together.</p> <p>Flutter is Google’s portable UI toolkit to build beautiful native apps on iOS and Android from a single codebase. Flutter Study Jams are a great opportunity to get together to learn and practice this technology in person.</p> <p>👨\u200d💻We prepared a list of awesome tutorials, so you can create something on your own, all the while we are there to help you in case you get stuck.<br/>🐧You can also bring your own ideas or work on open-source projects.<br/>❓You can come with questions, we’ll do our best to help you with any issue you bring.<br/>🎤At the end of the event, you’ll have the opportunity to show to the rest of us what you worked on (presenting is optional, but encouraged).</p> <p>I highly recommend you complete the Flutter installation guide and the Test drive before the event. Installing everything (Xcode, Android Studio, emulators, simulators, enabling development mode on your phone) can take some time, especially if you are doing it the first time. You can get the most out of this event if you successfully run the Flutter example app (click on floating action button to increment counter) on either an emulator/simulator or on a physical device. If you have Flutter installed on your computer, check your version and upgrade if necessary.</p> <p>IMPORTANT</p> <p>💻You need to bring your own computer.<br/>📱Bring cables to connect your phone to your laptop, if you’d like to develop on a physical device (aka mobile phone).<br/>⚡Don’t forget your charger.<br/>👩\u200d💻Finish the Installation Guide before the event. <br/>🏎Finish the Test drive before the event. </p> <p>LOCATION</p> <p>📍The event\'s location, food, and drinks are provided by SinnerSchrader Deutschland GmbH</p> <p>CONTRIBUTE</p> <p>🗣️ If you would like to share your story with Flutter, contact me! I\'m already organizing the next events and we have slots for speakers.</p> <p>🍕 Would your company like to host one of our upcoming events? Send me a message!</p> ',
        how_to_find_us: 'Follow the Flutter Meetup signs to find us. If you have issues finding us, send us a message.',
        visibility: 'public'
      },
      {
        created: 1560289481000,
        duration: 10800000,
        id: '262237645',
        name: 'Terminology & Semantics - Defining and Managing Meaning in Documentation',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561566600000,
        local_date: '2019-06-26',
        local_time: '18:30',
        updated: 1560289925000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 14,
        venue: {
          id: 26450415,
          name: 'Nymphenburger Str. 82',
          lat: 48.15009689331055,
          lon: 11.546968460083008,
          repinned: true,
          address_1: 'Nymphenburger Str. 82',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1542040675000,
          name: 'Write the Docs Munich',
          id: 30511791,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'write-the-docs-muc',
          who: 'Documentarians',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/write-the-docs-muc/events/262237645/',
        description: '<p>Defining what we mean by the terms that we use in documentation is not always straightforward. It takes work to fully determine semantics, and to manage terminology so that we\'re communicating with clarity, confidence and consistency.</p> <p>If you\'re interested in this subject, if you have a burning question, or if you\'d just like to come along and yap about docs with some very nice people, feel free to join us at our next Meetup!</p> <p>Co-host David Elliott will give a short introductory presentation. We then invite anyone interested in giving a presentation or talk, whether on the topic of terminology or anything else concerning documentation, to please volunteer ASAP. We\'ll then add you to the billing.</p> <p>Pizza, snacks and drinks will be available on the night.</p> ',
        how_to_find_us: 'By U-Bahn, take the U1 or U7 to Mailingerstraße. The office is right by the station.',
        visibility: 'public'
      },
      {
        created: 1553245571000,
        duration: 7200000,
        id: '259980020',
        name: 'WERK1Academy powered by 10DaysofDesign | Design Thinking',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561474800000,
        local_date: '2019-06-25',
        local_time: '17:00',
        updated: 1559916214000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 30,
        venue: {
          id: 26052503,
          name: 'WERK1 München',
          lat: 48.123779296875,
          lon: 11.608209609985352,
          repinned: true,
          address_1: 'Atelierstraße 29',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1458124246000,
          name: 'WERK1',
          id: 19716609,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'WERK1munich',
          who: 'movers and shakers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/WERK1munich/events/259980020/',
        description: '<p>TICKETKAUF NUR ÜBER EVENTBRITE - Kosten 40€<br/></p> <p>How to use Design Thinking to turn problems into solutions in just 2 hours!</p> <p>Nutzerzentrierte Produktentwicklung: wie kann man mit Hilfe von Design Thinking in kurzer Zeit Konzepte für innovative und nachgefragte Produkte &amp; Dienstleistungen entwickeln? Innovationsprozesse &amp; Methoden, die gezielt Kreativität fördern und intuitiv in den Team Arbeitsalltag integriert werden können.</p> <p>Wann: Di, 25.06. 17-19h -- Vortrag mit anschließendem Networking &amp; Drinks<br/>Wo: WERK1, Atelierstr. 29 (Raum: „Workshopraum”)<br/>Wer: Startups &amp; Coworker aus dem Münchner ecosystem</p> <p>Referenten: Thyra Wegener &amp; Patricia Titz | 10DaysofDesign</p> <p>Die Veranstaltung wird auf deutsch sein!</p> ',
        how_to_find_us: 'access by car only via “Piusstraße”, coming by S-Bahn Ostbahnhof enter Werksviertel on.',
        visibility: 'public'
      },
      {
        created: 1556020305000,
        duration: 7200000,
        id: '260849735',
        name: 'AfterWERK meets Munich Startup',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1564070400000,
        local_date: '2019-07-25',
        local_time: '18:00',
        updated: 1558445578000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 44,
        venue: {
          id: 19782872,
          name: 'WERK1',
          lat: 48.12442398071289,
          lon: 11.607309341430664,
          repinned: true,
          address_1: 'Grafinger Straße 6',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1458124246000,
          name: 'WERK1',
          id: 19716609,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'WERK1munich',
          who: 'movers and shakers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/WERK1munich/events/260849735/',
        description: '<p>Once per month the Munich Startup Community meets at WERK1 for the famous „Feierabend-Bier“, snacks and wine!</p> <p>Join us for 1-2 pitches &amp; networking. If you are interested in pitching yourself write to [masked].</p> <p>In a nutshell<br/>– Thursday, 25th July 2019 || 6pm<br/>– Informal networking with snacks &amp; drinks<br/>– Meet Munich Entrepreneurs Startups &amp; Freelancers<br/>– max. 2 startup pitches, 5 minutes each</p> ',
        how_to_find_us: 'access by car only via Piusstraße, coming by S-Bahn Ostbahnhof enter Werksviertel on Speicherstraße.',
        visibility: 'public'
      },
      {
        created: 1560796687000,
        duration: 9000000,
        id: '262394320',
        name: 'A Night of React Hooks—Introduction to React Hooks and Hooks in ReactReason',
        rsvp_limit: 100,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561653000000,
        local_date: '2019-06-27',
        local_time: '18:30',
        updated: 1560797400000,
        utc_offset: 7200000,
        waitlist_count: 12,
        yes_rsvp_count: 100,
        venue: {
          id: 26376748,
          name: 'SCOUT24 AG',
          lat: 48.13581466674805,
          lon: 11.613348007202148,
          repinned: true,
          address_1: 'Bothestraße 11-15',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1439803798000,
          name: 'React Munich',
          id: 18840725,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'reactmunich',
          who: 'Reactors',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/reactmunich/events/262394320/',
        description: '<p>A night of React Hooks! Martin Lechner will start with an introduction to React Hooks, and Tobias Timm takes it a step further in his talk about hooks in ReasonReact (and more)!</p> <p>Big thanks to Scout24 for hosting this meetup! There will of course be food and drinks, and a great rooftop balcony for mingling.</p> <p>*If you\'re interested in giving a talk at React Munich, please contact us!*</p> <p>Schedule:<br/>6:30pm—Open doors, food &amp; drinks</p> <p>7:00pm—Yet Another Introduction to Hooks by Martin Lechner (@m4nl5r, Scout24)</p> <p>Hooks took the react community by storm. Martin will give a quick introduction and share his experiences from first trys to custom hooks.</p> <p>8:00pm—Hooked for a Reason by Tobias Timm (@tbstimm, ProSiebenSat.1)</p> <p>ReasonReact released the new JSX 3 syntax, which makes it easier than ever to write quality type safe React code with ReasonML. You have never heard of ReasonML? No problem, we\'ve got you covered! In this talk Tobias will give you a crash course to ReasonML, shows you how to use the recently added Hooks efficiently and also covers topics like GraphQL, CSS-In-JS and testing. So you can start right off the bat your next project with a good reason.</p> ',
        how_to_find_us: '5th floor',
        visibility: 'public'
      },
      {
        created: 1560888210000,
        duration: 7200000,
        id: '262425061',
        name: '#WasMitBildung Konstruktiv',
        rsvp_limit: 15,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1563381000000,
        local_date: '2019-07-17',
        local_time: '18:30',
        updated: 1560939194000,
        utc_offset: 7200000,
        waitlist_count: 3,
        yes_rsvp_count: 15,
        venue: {
          id: 25967247,
          name: 'KEB München e.V.',
          lat: 48.13961410522461,
          lon: 11.569206237792969,
          repinned: false,
          address_1: 'Kapellenstraße 4',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1550657766000,
          name: 'WasMitBildung',
          id: 31210786,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'WasMitBildung',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/WasMitBildung/events/262425061/',
        description: '<p>Wir hatten uns für das nächste Event nun etwas Zeit gelassen. Nun ist es endlich wieder so weit: wir treffen uns zu einer neuen Runde #WasMitBildung.</p> <p>Bisher hatten wir ja einen Stammtischcharakter mit offenen Themen und haben noch nach konkreten Inhalten gesucht. Daher freuen wir uns umso mehr, das unser nächstes Event unter dem Motto „Konstruktivismus“ und „Rollenverständnis von Lernbegleitern“ steht.</p> <p>Zunächst stellen wir euch eine aktuelle Weiterbildung zum Lernbegleiter (in Hinblick auf digitale Medien) vor und wollen mit euch vor allem auf das Thema verändertes „Rollenverständnis“ eingehen. Basis ist die konstruktivistische Lerntheorie. Selbstverständlich gibt es dazu einen kleinen Input von uns, jedoch ist das Ziel in die Diskussion zu gehen.<br/>Wie seht ihr konstruktivistische Szenarien? Was setzt ihr wie um? Was interessiert euch daran? Wie geht ihr mit veränderten Rollen um?</p> <p>Bitte beachtet: Wir mussten die Teilnehmerzahl aufgrund der Räumlichkeiten begrenzen. Nehmt nur teil, wenn ihr wirklich an diesem Austausch interessiert seid. Seid bitte auch so fair und sagt ab, wenn ihr nicht könnt, damit auch jemand auf der Warteliste reinkommt.</p> <p>Diese Veranstaltung findet in Kooperation mit der KEB München und Freising e.V. statt, die uns diesmal in der Kapellenstrasse 4, 80333 München begrüßen wird.</p> ',
        visibility: 'public'
      }
    ]
}
export { mockEvents };